{
 "title": "Thousand Node Validator",
 "description": "Polkadot/Kusama 1KV Monitor. Combines Linux node exporter, substrate exporter and 1kv exporter data",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Active Validators",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "onekv_active", "legendFormat": "{{validator_name}}" }
   ]
  },
  {
   "title": "Invalid Validators",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "onekv_invalidity", "legendFormat": "{{validator_name}}" }
   ]
  },
  {
   "title": "Offline Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "onekv_offline_accumulated  ", "legendFormat": "{{validator_name}}" }
   ]
  },
  {
   "title": "Self Stake",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "onekv_bonded", "legendFormat": "{{validator_name}}  " }
   ]
  },
  {
   "title": "Unclaimed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "onekv_unclaimed_eras", "legendFormat": "{{validator_name}}" }
   ]
  },
  {
   "title": "Total Era Inclusion",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "onekv_inclusion", "legendFormat": "{{validator_name}}" }
   ]
  },
  {
   "title": "Span Inclusion",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "onekv_span_inclusion", "legendFormat": "{{validator_name}}" }
   ]
  },
  {
   "title": "1kv Ranking",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "onekv_rank", "legendFormat": "{{validator_name}}" }
   ]
  },
  {
   "title": "Sync State",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "abs((polkadot_block_height{status=\"best\"} - ignoring (status) polkadot_block_height{status=\"sync_target\"}))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Validator Peers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "polkadot_sub_libp2p_peers_count",
     "legendFormat": "peers - {{instance}}"
    }
   ]
  },
  {
   "title": "Validator Rewards",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "polkadot_proposer_block_constructed_count",
     "legendFormat": "total blocks constructed {{instance}}"
    },
    {
     "expr": "increase(polkadot_parachain_approvals_produced_total[$__interval])",
     "legendFormat": "parachain approval {{instance}}"
    },
    {
     "expr": "increase(polkadot_proposer_block_constructed_count[$__interval])",
     "legendFormat": "NEW blocks constructed {{instance}}"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "gauge",
   "gridPos": { "h": 19, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "timestamp(polkadot_process_start_time_seconds) - polkadot_process_start_time_seconds",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "connections / 15s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(polkadot_sub_libp2p_requests_out_failure_total[$__interval])*10",
     "legendFormat": "failed in conn {{instance}} - {{reason}}"
    },
    {
     "expr": "rate(polkadot_sub_libp2p_requests_in_success_total_count[$__interval])*10",
     "legendFormat": "in success {{instance}} "
    },
    {
     "expr": "rate(polkadot_sub_libp2p_incoming_connections_handshake_errors_total[$__interval])*10",
     "legendFormat": "failed in conn {{instance}} - {{reason}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 15, "w": 10, "x": 10, "y": 12 } },
  {
   "title": "Traffic Outbound",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"(en|eth|nic).*\"}[$__rate_interval])*8",
     "legendFormat": "OUT: {{instance}} {{device}}"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"(en|eth|nic).*\"}[$__rate_interval])*8",
     "legendFormat": "IN: {{instance}} {{device}}"
    }
   ]
  }
 ]
}